name = "BlackOps Unleashed"
uid = "9e8ea941-c306-aaaf-b367-f00000000005"
version = 10
copyright = "2009 Exavier Macbeth, lt_hawkeye, orangeknight"
description = "The ultimate unit pack, re-engineered for FAF"
author = "Exavier Macbeth, lt_hawkeye, orangeknight - Revamped 2016 by IceDreamer"
icon = "/mods/BlackOpsUnleashed/icon.bmp"
selectable = true
enabled = true
exclusive = false
ui_only = false
special_thanks = "Uveso, Softles, Nojoke185, ZephyrWarrior, Raistlfiren, Nocaps"
