name = "SharedArmies"
uid = "bea51941-c306-aaaf-b367-u00000004000"
version = 4
copyright = "2017 Eximius, Sheeo, IceDreamer, MrNukalizer"
description = "Allows joint control of a single army"
author = "Eximius, Sheeo, IceDreamer, MrNukalizer"
selectable = true
enabled = true
exclusive = false
ui_only = false
