name = "balancepreview"
uid = "6438ab5b-7be9-11e4-f421-278bbbf75aae"
version = 16
copyright = ""
description = "Balance Preview for Q1 2015"
author = "FAF"
url = ""
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
